import type { Metadata } from 'next'
import Link from 'next/link'
import { LEGAL_META } from '@/lib/legal/constants'

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description: `Privacy Policy for ${LEGAL_META.productName} — ${LEGAL_META.companyName}.`,
}

export default function PrivacyPolicyPage() {
  const { productName, companyName, companyAddress, supportEmail, effectiveDateIso, effectiveDateDisplay } = LEGAL_META

  return (
    <article className="mx-auto max-w-3xl px-4 sm:px-6 text-sm leading-relaxed text-foreground/90">
      <h1 className="text-2xl font-semibold tracking-tight text-foreground">Privacy Policy</h1>
      <p className="mt-2 text-foreground/55">
        Last updated: <time dateTime={effectiveDateIso}>{effectiveDateDisplay}</time>
      </p>

      <section className="mt-10 space-y-4">
        <h2 className="text-base font-semibold text-foreground">1. Who we are</h2>
        <p>
          This Privacy Policy describes how {companyName} (“{companyName},” “we,” “us,” or “our”) collects, uses,
          discloses, and otherwise processes personal information in connection with {productName}, our web-based
          software and related services (collectively, the “Service”). By using the Service, you acknowledge this
          Policy.
        </p>
        <p>
          If you use the Service on behalf of an organization, you represent that you are authorized to bind that
          organization, and “you” includes both you and the organization.
        </p>
      </section>

      <section className="mt-8 space-y-4">
        <h2 className="text-base font-semibold text-foreground">2. Scope</h2>
        <p>
          This Policy applies to personal information we process through the Service, our websites and applications that
          link to this Policy, and related communications (for example, support emails). It does not apply to third-party
          sites or services that we do not control, even if linked from the Service.
        </p>
      </section>

      <section className="mt-8 space-y-4">
        <h2 className="text-base font-semibold text-foreground">3. Personal information we collect</h2>
        <p>Depending on how you use the Service, we may collect the following categories of information:</p>
        <ul className="list-disc space-y-2 pl-5">
          <li>
            <strong>Identifiers and account data.</strong> Name, email address, user ID, workspace or organization
            identifiers, job title or role where you provide it, and similar account attributes.
          </li>
          <li>
            <strong>Authentication and security data.</strong> Login timestamps, session tokens, device or browser
            identifiers, IP address, and security-related logs used to protect accounts and detect abuse.
          </li>
          <li>
            <strong>Customer content (“Project Data”).</strong> Information you or your collaborators submit to the
            Service, including property addresses, jurisdiction or city selections, uploaded plans or documents (for
            example PDFs or images), feasibility inputs, notes, comments, review decisions, billing-related workspace
            metadata, and outputs generated by the Service (for example reports or structured analysis).
          </li>
          <li>
            <strong>Commercial information.</strong> Records of products or services purchased, credits consumed,
            subscription status, and related billing metadata. Payment card numbers are collected and processed by our
            payment processor; we do not store full payment card numbers on our own systems.
          </li>
          <li>
            <strong>Internet or other electronic network activity.</strong> Log data, diagnostics, approximate location
            derived from IP address, referring URLs, and usage information such as pages or features accessed and
            interaction timestamps.
          </li>
          <li>
            <strong>Communications.</strong> Content of emails or in-product messages you send to us, including support
            requests and feedback.
          </li>
          <li>
            <strong>Inferences.</strong> We may derive information from the above data to operate, secure, and improve
            the Service (for example, fraud risk signals or product usage patterns).
          </li>
        </ul>
        <p>
          We do not use the Service to collect sensitive categories of information defined under applicable law (such as
          government identifiers, precise geolocation, or health data) except where you voluntarily include such
          information in Project Data. If you include sensitive information in uploads or text fields, you instruct us
          to process it solely to provide the Service.
        </p>
      </section>

      <section className="mt-8 space-y-4">
        <h2 className="text-base font-semibold text-foreground">4. Sources of personal information</h2>
        <p>We collect personal information from:</p>
        <ul className="list-disc space-y-2 pl-5">
          <li>You, when you register, complete forms, upload files, purchase services, or communicate with us;</li>
          <li>Your collaborators or workspace administrators, when they invite you or add you to a workspace;</li>
          <li>Automated technologies when you use the Service (for example cookies, pixels, or server logs); and</li>
          <li>Third parties such as authentication providers, payment processors, or data partners where you direct us to
            integrate them or where necessary to provide a feature you request.</li>
        </ul>
      </section>

      <section className="mt-8 space-y-4">
        <h2 className="text-base font-semibold text-foreground">5. How we use personal information</h2>
        <p>We use personal information for the following business purposes:</p>
        <ul className="list-disc space-y-2 pl-5">
          <li>Providing, operating, maintaining, and improving the Service, including AI-assisted analysis and report generation;</li>
          <li>Authenticating users, preventing fraud and abuse, enforcing rate limits, and protecting security and integrity;</li>
          <li>Processing payments, fulfilling orders, managing credits and subscriptions, and sending transactional notices;</li>
          <li>Communicating with you about the Service, including support, service announcements, and policy updates;</li>
          <li>Complying with legal obligations and responding to lawful requests from public authorities;</li>
          <li>Exercising or defending legal claims; and</li>
          <li>Conducting internal research and analytics in de-identified or aggregated form where permitted.</li>
        </ul>
        <p>
          We do not use personal information for automated decision-making that produces legal or similarly significant
          effects solely by automated means without human involvement, except as inherent to the analytical features you
          request (for example ranking or summarizing inputs you supply). You remain responsible for professional and
          business decisions based on Service outputs.
        </p>
      </section>

      <section className="mt-8 space-y-4">
        <h2 className="text-base font-semibold text-foreground">6. How we disclose personal information</h2>
        <p>We may disclose personal information in the following circumstances:</p>
        <ul className="list-disc space-y-2 pl-5">
          <li>
            <strong>Service providers and subprocessors.</strong> Vendors that process information on our behalf under
            written terms, including hosting and infrastructure providers, database and authentication services, payment
            processing (for example Stripe), email delivery, logging and error monitoring, customer support tools, and
            third-party AI or machine-learning model providers used to generate or refine outputs.
          </li>
          <li>
            <strong>Workspace visibility.</strong> Project Data may be visible to other users in the same workspace or
            project according to permissions and product features you or your administrator configure (for example
            collaborators or reviewers).
          </li>
          <li>
            <strong>Legal and safety.</strong> When we believe disclosure is required by law, regulation, legal process,
            or governmental request, or is necessary to protect the rights, property, or safety of {companyName}, our
            users, or the public.
          </li>
          <li>
            <strong>Business transfers.</strong> In connection with a merger, acquisition, financing, reorganization, or
            sale of assets, personal information may be transferred as part of that transaction, subject to standard
            confidentiality arrangements.
          </li>
          <li>
            <strong>With your direction.</strong> When you integrate third-party services or export data, disclosures may
            occur as you instruct.
          </li>
        </ul>
        <p>
          We do not sell your personal information for monetary consideration. We do not share personal information for
          cross-context behavioral advertising as defined under the California Privacy Rights Act (“CPRA”) as of the
          Last updated date above; if our practices change, we will update this Policy and provide any required controls
          or notices.
        </p>
      </section>

      <section className="mt-8 space-y-4">
        <h2 className="text-base font-semibold text-foreground">7. Cookies and similar technologies</h2>
        <p>
          We and our service providers may use cookies, local storage, pixels, and similar technologies to operate the
          Service (for example session management, security, preferences, and load balancing) and to understand aggregate
          usage. You can control cookies through your browser settings; disabling certain cookies may affect Service
          functionality.
        </p>
        <p>
          As of the Last updated date above, we do not deploy third-party advertising or social-media pixels on FeasiAI,
          and we do not use cookies for cross-context behavioral advertising. If we introduce optional analytics or
          marketing cookies in the future, we will update this Policy and, where required, present a consent or opt-out
          control before those technologies load.
        </p>
        <p>
          Payment pages may load scripts controlled by Stripe, Inc. When you interact with Stripe checkout, Stripe’s own
          privacy policy and cookie practices apply to that experience in addition to this Policy.
        </p>
      </section>

      <section className="mt-8 space-y-4">
        <h2 className="text-base font-semibold text-foreground">8. Retention</h2>
        <p>
          We retain personal information for as long as necessary to fulfill the purposes described in this Policy,
          unless a longer period is required or permitted by law. Criteria used to determine retention periods include
          the nature of the information, whether you maintain an active account, whether Project Data is needed to
          provide ongoing services or resolve disputes, and legal, tax, or accounting requirements. Workspace
          administrators may delete or export certain content subject to product capabilities; soft-deleted workspaces
          may be retained for a defined period before permanent deletion as described in product documentation or
          administrator settings.
        </p>
      </section>

      <section className="mt-8 space-y-4">
        <h2 className="text-base font-semibold text-foreground">9. Security</h2>
        <p>
          We implement administrative, technical, and organizational measures designed to protect personal information
          against unauthorized access, loss, or alteration. These measures include access controls, encryption in
          transit where supported, and vendor security reviews appropriate to risk. No method of transmission or storage
          is completely secure; we cannot guarantee absolute security.
        </p>
      </section>

      <section className="mt-8 space-y-4">
        <h2 className="text-base font-semibold text-foreground">10. United States — California residents</h2>
        <p>
          If you are a California resident, the CPRA may provide you with specific rights regarding personal information
          that identifies, relates to, describes, is reasonably capable of being associated with, or could reasonably be
          linked with you or your household. Subject to exceptions under law, those rights may include:
        </p>
        <ul className="list-disc space-y-2 pl-5">
          <li>
            <strong>Right to know and access.</strong> You may request the categories and specific pieces of personal
            information we have collected, the categories of sources, business or commercial purposes, and categories of
            third parties to whom we disclose personal information.
          </li>
          <li>
            <strong>Right to delete.</strong> You may request deletion of personal information we collected from you,
            subject to certain exceptions (for example where retention is necessary to complete a transaction or comply
            with law).
          </li>
          <li>
            <strong>Right to correct.</strong> You may request correction of inaccurate personal information we maintain.
          </li>
          <li>
            <strong>Right to opt out of sale or sharing.</strong> As stated above, we do not sell personal information and
            do not share it for cross-context behavioral advertising as of the Last updated date. If our practices
            change, we will describe any opt-out mechanism required by law.
          </li>
          <li>
            <strong>Right to limit use of sensitive personal information.</strong> Where applicable, you may have the
            right to limit certain uses of sensitive personal information; we use such information only as permitted by
            law and to provide the Service as described here.
          </li>
          <li>
            <strong>Non-discrimination.</strong> We will not discriminate against you for exercising CPRA rights, for
            example by denying services or charging different prices, unless permitted by law.
          </li>
        </ul>
        <p>
          <strong>How to submit a request.</strong> For a portable copy of information we associate with your account, use
          <strong> Settings</strong> (<strong>Download data export</strong>) while signed in. For other requests, email{' '}
          <a href={`mailto:${supportEmail}`} className="text-primary underline-offset-4 hover:underline">
            {supportEmail}
          </a>{' '}
          with “California Privacy Request” in the subject line. We will verify your request using information associated
          with your account. Authorized agents may submit requests on your behalf with written authorization; we may
          require you to verify your identity directly with us.
        </p>
        <p>
          Under California Civil Code § 1798.83 (Shine the Light), California residents may request certain information
          regarding disclosure of personal information to third parties for their direct marketing purposes. We do not
          disclose personal information to third parties for their direct marketing purposes as traditionally defined by
          that statute; if that changes, we will provide a designated contact method.
        </p>
      </section>

      <section className="mt-8 space-y-4">
        <h2 className="text-base font-semibold text-foreground">11. Other U.S. states</h2>
        <p>
          Residents of Colorado, Connecticut, Virginia, Utah, and other states with comprehensive privacy laws may have
          similar rights to access, delete, correct, and opt out of certain processing, including targeted advertising or
          sales where applicable. To exercise rights, contact us at{' '}
          <a href={`mailto:${supportEmail}`} className="text-primary underline-offset-4 hover:underline">
            {supportEmail}
          </a>
          . If we deny your request, you may appeal by replying to our decision email within the timeframe stated in that
          message, where appeals are required by law.
        </p>
      </section>

      <section className="mt-8 space-y-4">
        <h2 className="text-base font-semibold text-foreground">12. International users</h2>
        <p>
          The Service is operated from the United States. If you access the Service from outside the United States, you
          consent to the transfer, storage, and processing of personal information in the United States and other
          jurisdictions where we or our subprocessors operate, which may have different data protection rules than your
          country. Where required by applicable law, we will implement appropriate safeguards for international
          transfers.
        </p>
      </section>

      <section className="mt-8 space-y-4">
        <h2 className="text-base font-semibold text-foreground">13. Children</h2>
        <p>
          The Service is not directed to individuals under 16 years of age, and we do not knowingly collect personal
          information from children under 16. If you believe we have collected information from a child under 16,
          contact us at{' '}
          <a href={`mailto:${supportEmail}`} className="text-primary underline-offset-4 hover:underline">
            {supportEmail}
          </a>{' '}
          and we will take appropriate steps to delete it.
        </p>
      </section>

      <section className="mt-8 space-y-4">
        <h2 className="text-base font-semibold text-foreground">14. Changes to this Policy</h2>
        <p>
          We may update this Privacy Policy from time to time. We will post the revised Policy on this page and update
          the “Last updated” date. If changes are material, we will provide additional notice as required by law (for example
          a prominent notice in the Service or email to the address on file).
        </p>
      </section>

      <section className="mt-8 space-y-4">
        <h2 className="text-base font-semibold text-foreground">15. Contact us</h2>
        <p>
          For questions about this Privacy Policy or our privacy practices, contact:
        </p>
        <p className="pl-0">
          {companyName}
          <br />
          {companyAddress}
          <br />
          Email:{' '}
          <a href={`mailto:${supportEmail}`} className="text-primary underline-offset-4 hover:underline">
            {supportEmail}
          </a>
        </p>
      </section>

      <p className="mt-12 text-xs text-foreground/45">
        <Link href="/legal" className="text-primary hover:underline">
          ← Legal
        </Link>
        {' · '}
        <Link href="/legal/terms" className="text-primary hover:underline">
          Terms of Service
        </Link>
      </p>
    </article>
  )
}
